name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  setup-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: 16.x
          cache: npm
      - name: Validate cache
        run: npm ci

  test:
    name: Node v${{ matrix.node-version }} on ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]
        os: [ubuntu-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    needs: setup-npm
    steps:
      - uses: actions/checkout@v3
      - name: Get npm cache
        id: npm-cache
        run: echo "::set-output name=dir::$(npm config get cacheFolder)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-npm-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and build
        run: npm ci
      - name: Run tests with coverage
        run: npm run test

  lint:
    name: build-lint
    runs-on: ubuntu-latest
    needs: setup-npm
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: 16.x
          cache: npm
      - name: Install
        run: npm ci
      - name: Run prettier
        run: npm run lint
